[project]
name = "fastapi-headless-cms"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.16.5",
    "fastapi>=0.116.1",
    "pydantic>=2.11.7",
    "sqlalchemy>=2.0.43",
    "uvicorn[standard]>=0.35.0",
]
